name: Day 5 CI with Docker

on:
  push:
    paths:
      - 'Day-5-github-actions/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-app ./Day-5-github-actions

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Image
        run: docker tag my-app ${{ secrets.DOCKER_USERNAME }}/day5-app:latest

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/day5-app:latest
