name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      run: docker build -t ashytcloud/day5-app:latest ./day-15-k8s-cicd

    - name: Push Docker Image
      run: docker push ashytcloud/day5-app:latest

    - name: Set up kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f day-15-k8s-cicd/deployment.yml --insecure-skip-tls-verify=true
        kubectl apply -f day-15-k8s-cicd/service.yml  --insecure-skip-tls-verify=true
